cc_library(
    name = "DNNObjectDetect",
    srcs = ["DNNObjectDetect.cpp"],
    hdrs = ["DNNObjectDetect.h"],
    visibility = ["//visibility:public"],
    deps = [
      "@opencv//:opencv",
      "//src/utils:utils"
    ]
)