cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "@opencv//:opencv",
        "@ie//:ie",
        "//src/utils:utils",
        "//src/DNNObjectDetect:DNNObjectDetect"
    ],
)